#!/bin/bash

# connect_instance
source ./utils/connect
source ./utils/gets

function connect(){
	function usage_exit(){
		echo "Usage: $0 [-i IPAddress]"
		echo -e "\t-i: IP Address (Default latest launch instance)"
		exit 1
	}

	while getopts ":i:h" OPT;do
		case $OPT in
			i) CONNECT_IP=$OPTARG
				;;
			h) usage_exit
				;;
			\?) usage_exit
				;;
		esac
	done

	if [ -z "$1" ]; then
		get_username
		
		if [ -z "$USERNAME" ]; then
			echo "no username..."
			exit 1
		fi
	else
		USERNAME="$1"
	fi

	if [ -n "$CONNECT_IP" ]; then
		echo "Connect IP => $CONNECT_IP"
	else
		echo "Connect Latest Launch Instance"
	fi 
	connect_instance $USERNAME $CONNECT_IP
}

connect $@
