#!/bin/bash

source utils/create

function create(){
	function usage_exit(){
		echo "Usage: $0 [-i Init Script file]"
		echo -e "\t-i: Init Script file (default \"file://init.sh\")"
		exit 1
	}
	while getopts ":i:h" OPT; do
		case $OPT in
			i) INIT_SCRIPTS=$OPTARG
				;;
			h) usage_exit
				;;
			\?) usage_exit
				;;
		esac
	done

	INIT_SCRIPTS=${INIT_SCRIPTS:-"file://init.sh"}

	SCRIPTS=$(cat $INIT_SCRIPTS)

	echo "Init Script File => $INIT_SCRIPTS"
	# Creating Instance
	create_mysql_ec2 "$INIT_SCRIPTS"
}
