#!/bin/bash

# get_tag
source utils/gets
# get_ip_from_tag
source utils/ip

# ip TAGS STATE
function ip(){
	function usage_exit(){
		echo "Usage: $0 [-t Tag] [-s State]"
		echo -e "\t-t: Search IP Address with Tag"
		echo -e "\t-s: Search Ip Address with State"
		echo -e "\t-q: Quiet Output"
		exit 1
	}
	local OPT OPTARG OPTIND QUIET_OPTION
	while getopts ":t:s:qh" OPT; do
		case $OPT in
		t)	TAGS=$OPTARG
			;;
		s)	STATE=$OPTARG
			;;
		q)	QUIET_OPTION="-q"
			;;
		h)	usage_exit
			;;
		\?)	usage_exit
			;;
		esac
	done

	if [ -z "$TAGS" ];then
		get_tag
	fi
	if [ -z "$TAGS" ];then
		echo "Not Tag found..."
		usage_exit
	fi
	STATE=${STATE:-"running"}
	get_ip_from_tag $QUIET_OPTION $TAGS $STATE
}

ip $@
