#!/bin/bash

# get_imageid,get_instancetype,get_securitygroup,
# get_keybname,get_subnetid,get_tag
source ./utils/gets
# create_tag_function
source ./utils/create_tag

#
#       Create EC2 Server
#
# IMAGEID => image id
# INSTANCETYPE => aws instance type
# KEYNAME => key pair name
# SG => security group ids
# SUBNETID => subnet id
#
function create_ec2(){
        get_imageid
        get_instancetype
        get_securitygroup
        get_keyname
        get_subnetid
        get_tag

        if [ -n "$1" ];then
                USERDATA="--user-data $1"
                echo "Init Scripts:"
                echo "$USERDATA"
        else
                USERDATA=
                echo "Warning: No Init Scripts"
        fi
	echo $IMAGEID
	echo $INSTANCETYPE
	echo $KEYNAME
	echo $SG
	echo $SUBNETID
	echo $USERDATA
        INSTANCES=$(aws ec2 run-instances \
                --image-id $IMAGEID \
                --count ${2:-1}         \
                --instance-type $INSTANCETYPE \
                --key-name $KEYNAME \
                --security-group-ids $SG \
                --subnet-id $SUBNETID \
                $USERDATA
                )

        INSTANCE_IDS=$(echo $INSTANCES | jq -r ".Instances[].InstanceId")
        CREATE_INSTANCE_IDS=$INSTANCE_IDS
        for INSTANCE in $INSTANCE_IDS; do
                echo "Create Instance ID => $INSTANCE"
                # create tag
                create_tag_instance $INSTANCE
        done
        # wait in background
        wait_for_running $CREATE_INSTANCE_IDS &
        wait_for_status_ok $CREATE_INSTANCE_IDS &
}

# wait for creating EC2 instances
function wait_for_running(){
        # argument check
        if [ -z "$*" ]; then
                echo "nothing waiting instace ids..."
                exit 1
        fi
        echo "Wating for status \"running\" => $@"
        aws ec2 wait instance-running \
        --instance-ids $*
        echo "Now Running $CREATE_INSTANCE_IDS!!!"
}
function wait_for_status_ok(){
        # argument check
        if [ -z "$*" ]; then
                echo "nothing waiting instace ids..."
                exit 1
        fi
        aws ec2 wait instance-status-ok \
        --instance-ids $*
        echo "Now Status OK $CREATE_INSTANCE_IDS!!!"
}

