#!/bin/bash

# get_securitygroup
source utils/gets
#
# $1 => PROTOCOL
# $2 => PORT
# $3 => CIDR
#
function add_sg_in(){
	function usage_exit(){
		echo "Usage: $0 PROTOCOL PORT CIDR"
		exit 1
	}
        get_securitygroup
        if [ -z "$SGID" ]; then
                echo "not found security group..."
                exit 1
        fi

        if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
		usage_exit
        fi

        aws ec2 authorize-security-group-ingress \
        --group-id "$SGID" --protocol "$1" --port "$2" \
        --cidr "$3"
        aws ec2 describe-security-groups \
        --group-ids "$SGID"
}
