#!/bin/bash

# get_tag
source utils/gets
# tag_check
source utils/check

# required: $TAGS (terminate all match TAG instance)
# All Instances
# return $TERMINATE_INSTANCE_IDS
function terminate_allinstances(){
        get_tag
        if [ -z "$TAGS" ]; then
                echo "not found TAGS..."
        fi
        tag_check $TAGS
        TERMINATE_INSTANCE_IDS=$( \
                aws ec2 describe-instances --filter Name=instance-state-name,Values=running | \
                jq -r ".Reservations[].Instances | \
                select(.[].State.Name==\"running\") | \
                select(.[].Tags != null) | \
                select(.[].Tags[].Key==\"$KEY\") | \
                select(.[].Tags[].Value==\"$VALUE\") | \
                .[].InstanceId"
        )
        if [ -z "$TERMINATE_INSTANCE_IDS" ]; then
		echo "no running instance..."

		# Check have no tag instance
		NO_TAG_INSTANCES=$(aws ec2 describe-instances | jq -r ".Reservations[].Instances | select(.[].Tag == null) | .[].InstanceId")
		if [ -n "$NO_TAG_INSTANCE" ]; then
			echo "WARNING: You have No Tag Instances!!!"
			for INSTANCE in $NO_TAG_INSTANCES; do
				echo "$INSTANCE"
			done
		fi

                exit 1
        fi
        echo -e "Now Running Instances($TAGS):\n$TERMINATE_INSTANCE_IDS"
        aws ec2 terminate-instances --instance-ids $TERMINATE_INSTANCE_IDS
        echo "Terminated $TERMINATE_INSTANCE_IDS"
}
